apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
     labels:
      app: frontend
    spec:
     containers:
     - name: frontend
       image: k8s-demo-shop-frontend:proxy-v1
       imagePullPolicy: Never
       ports:
       - containerPort: 80
       livenessProbe:
         httpGet:
           path: /
           port: 80
         initialDelaySeconds: 10
         periodSeconds: 10
       readinessProbe:
         httpGet:
           path: /
           port: 80
         initialDelaySeconds: 5
         periodSeconds: 10
       resources:
         requests:
           cpu: "100m"
           memory: "128Mi"
         limits:
           cpu: "300m"
           memory: "256Mi"
