apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.pvc.name }}
spec:
  accessModes:
    - {{ .Values.redis.pvc.accessMode }}


  resources:
    requests:
      storage: {{ .Values.redis.pvc.storage }}
