apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccountName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.backend.rbac.roleName }}
rules:
  {{- toYaml .Values.backend.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.backend.rbac.roleBindingName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.backend.serviceAccountName }}
roleRef:
  apiGroup: {{ .Values.backend.rbac.roleRef.apiGroup }}
  kind: {{ .Values.backend.rbac.roleRef.kind }}
  name: {{ .Values.backend.rbac.roleRef.name }}
