apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secret.name }}


type: {{ .Values.backend.secret.type }}
stringData:
    DB_USER: {{ .Values.backend.secret.stringData.dbUser | quote }}
    DB_PASSWORD: {{ .Values.backend.secret.stringData.dbPassword | quote }}
    JWT_SERECT: {{ .Values.backend.secret.stringData.jwtSerect | quote }}
