name: Publish Images

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
    publish:
        name: Publish Images
        runs-on: ubuntu-latest

        steps:
            - name: Workflow Started
              run: echo "Publish workflows triggered successfully" 