name: Trivy Security Scan

on: 
    push:
        branches: [main]

jobs:
    trivy:
        runs-on: ubuntu-latest
        
        steps: 
          - uses: actions/checkout@v4

          - name: Build Backend Image
            run: docker build -t backend:scan ./backend

          - name: Run Trivy Scan
            uses: aquasecurity/trivy-action@v0.36.0
            with: 
                image-ref: backend:scan
                scanners: vuln
                vuln-type: os,library
                format: table
                exit-code: 1
                severity: CRITICAL,HIGH  